client: test3
# Which bot to deploy to. Type `test` or `stable`.
# If in test mode, you have 4 options to deploy:
# `test1` deploys to Floofy Den Test Bot
# `test2` deploys to Floofy Helper+
# `test3` deploys to Floofy Den Verification
# `test` deploys to all 3
discordAPIVersion: 10 # Which Discord API version to use

floofyHelper:
  levelPermissions:
    lvl4: "[  ]" # Owner
    lvl3: "[  ]" # Trusted Staff
    lvl2: "[  ]" # Staff
    lvl1: "[  ]" # Users

  tickets:
    tktAdmin: "[  ]"
    tktSupport: "[  ]"

  XP:
    msgRate: 4 # amount of points to award for each message sent
    msgCooldown: 100 # in milliseconds
    imgRate: 7 # amount of points to award for each image sent
    imgCooldown: 300 # in milliseconds
    vcRate: 10 # amount of points to award for being in VC for vcCooldown milliseconds
    vcCooldown: 1000
    xpBoost: "[  ]" # XP Boosting Roles

floofyHelper+:

floofyDenVerification:
  channel: "1010210431979233322" # Channel to send verification applications
  logChannel: "989982481107263568" # Channel to send verification logs

cronitor:
  Floofy Helper Bot:
    # configure monitor as a heartbeat
    type: "heartbeat"
    # When events will be sent to Cronitor (also supports cron and HH:MM 24hr time expressions)
    schedule: "every 30 seconds"
    # assertions based on data along with the heartbeat event
    assertions:
      - "metric.error_count < 3"
